language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - gemfiles/rails_2.3.gemfile
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_2.3.gemfile
before_script:
  - bundle install
script: "bundle exec rake spec"
